# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    mert:
                        password: $2y$12$j0F.AUqkRphRHU6XFk9Bq.M2VM/cy25rkijkKvTQeyqhAFYuu4wWm
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$j0F.AUqkRphRHU6XFk9Bq.M2VM/cy25rkijkKvTQeyqhAFYuu4wWm
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            security: true
            anonymous: ~
            logout_on_user_change: true
            http_basic: ~
            form_login:

            logout:
                path:   /logout
                target: /
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
      # require ROLE_ADMIN for /admin*
        - { path: ^/, roles: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
